version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_travel_app
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5440:5432"
    restart: always
